const SIZE = 32

const WIDTH = 25 // X
const HEIGHT = 15 // Y

const CANVAS_WIDTH = WIDTH * SIZE
const CANVAS_HEIGHT = HEIGHT * SIZE

const NORMALIZE_X = Math.floor(WIDTH / 2)
const NORMALIZE_Y = Math.floor(HEIGHT / 2)

const CENTER_WIDTH = NORMALIZE_X * SIZE 
const CENTER_HEIGHT = NORMALIZE_Y * SIZE

export { SIZE, WIDTH, HEIGHT, CANVAS_WIDTH, CANVAS_HEIGHT, NORMALIZE_X, NORMALIZE_Y, CENTER_WIDTH, CENTER_HEIGHT }