const SIZE = 16

const WIDTH = 43 // X
const HEIGHT = 29 // Y

const CANVAS_WIDTH = WIDTH * SIZE
const CANVAS_HEIGHT = HEIGHT * SIZE

const CENTER_WIDTH = Math.floor(WIDTH / 2) * SIZE
const CENTER_HEIGHT = Math.floor(HEIGHT / 2) * SIZE

export {CANVAS_WIDTH, CANVAS_HEIGHT, WIDTH, HEIGHT, SIZE, CENTER_WIDTH, CENTER_HEIGHT}